// File generated by template engine for the versat_wrapper.tpl template
// Do not make changes, versat will overwrite

#include <new>

#include <cstdint>
#include <cstdio>
#include <cassert>
#define Assert(x) assert(x)

#include "versat_accel.h" // TODO: Is this needed? We technically have all the data that we need to not depend on this header and removing this dependency could simplify the build process. Take a look later

#define ALIGN_UP(val,size) (((val) + (size - 1)) & ~(size - 1))
#define ALIGN_DOWN(val,size) (val & (~(size - 1)))

#define MIN(A,B) (((A) < (B)) ? (A) : (B))

#include "verilated.h"

// Needed to obtain the wire size of the unit from the verilated code.
// Since the verilated code is an "instantiation" of the unit, we do not have to bother with the possibility of wire not being concrete (because they depend on parameters). We can just use the values directly.
#include "VUnitWireInfo.h"

@{defines}

#ifdef TRACE

VerilatedContext* contextp = new VerilatedContext;

#ifdef TRACE_FST
#include "verilated_fst_c.h"
static VerilatedFstC* tfp = NULL;
#else
#include "verilated_vcd_c.h"
static VerilatedVcdC* tfp = NULL;
#endif

#endif // TRACE

#include "VVersat_verilator_wrapper.h"
#ifdef SIMULATE_LOOPS
#include "VSuperAddress.h"
#endif

struct DatabusAccess{
   int counter;
   int latencyCounter;
};

// ============================================================================
// Global data 

typedef VVersat_verilator_wrapper TopType;

static TopType* dut = NULL;
static int versat_empty_printf(const char* format,...){return 0;}
VersatPrintf versat_printf = versat_empty_printf;
bool CreateVCD;
bool SimulateDatabus;
bool versatInitialized;

static @{typeName}Config configBuffer = {};
static @{typeName}State stateBuffer = {};
static AcceleratorStatic staticBuffer = {};
static DatabusAccess databusBuffer[@{nIOs}] = {}; 

volatile @{typeName}Config* accelConfig = (volatile @{typeName}Config*) &configBuffer;
volatile @{typeName}State* accelState = (volatile @{typeName}State*) &stateBuffer;
volatile AcceleratorStatic* accelStatic = (volatile AcceleratorStatic*) &staticBuffer;

// ============================================================================
// Utilities

#pragma GCC poison printf // Do not call printf, call versat_printf

// TODO: Maybe this should not exist. There should exist one update function and every other function that needs to update stuff should just call that function. UPDATE as it stands should only be called inside the update function. Instead of having macros that call UPDATE, we should just call the update function directly inside the RESET macro and the START_RUN macro and so one. Everything depends on the update function and the UPDATE macro is removed and replaced inside the function. The only problem is that I do not know if the RESET macro can call the update function without something. Nonetheless, every "update" should go trough the update function and none should go through this macro.
#ifdef TRACE
#define UPDATE(unit) \
   unit->clk = 0; \
   unit->eval(); \
   if(CreateVCD) tfp->dump(contextp->time()); \
   contextp->timeInc(2); \
   unit->clk = 1; \
   unit->eval();
#else
#define UPDATE(unit) \
   unit->clk = 0; \
   unit->eval(); \
   unit->clk = 1; \
   unit->eval();
#endif

static char* Bin(unsigned int value){
   static char buffer[33];
   buffer[32] = '\0';

   unsigned int val = value;
   for(int i = 31; i >= 0; i--){
      buffer[i] = '0' + (val & 0x1);
      val >>= 1;
   }

   return buffer;
}

static const int INITIAL_MEMORY_LATENCY = 5;
static const int MEMORY_LATENCY = 0;

typedef char Byte;

// Everything is statically allocated

extern "C" void InitializeVerilator(){
#ifdef TRACE
  Verilated::traceEverOn(true);
#endif
}

static void CloseWaveform(){
#ifdef TRACE
  if(CreateVCD && tfp){
    tfp->close();
  }
#endif
}

extern "C" void VersatAcceleratorCreate(){
#ifdef TRACE
   if(CreateVCD){
   #ifdef TRACE_FST
      tfp = new VerilatedFstC;
   #else
      tfp = new VerilatedVcdC;
   #endif
   }
#endif
   TopType* self = new TopType();

   if(dut){
      versat_printf("Initialize function is being called multiple times\n");
      exit(-1);
   }

   dut = self;

#ifdef TRACE
  if(CreateVCD){
    self->trace(tfp, 99);
      
    #ifdef TRACE_FST
    tfp->open("system.fst");
    #else
    tfp->open("system.vcd");
    #endif

    atexit(CloseWaveform);
  }
#endif

  self->run = 0;
  self->clk = 0;
  self->rst = 0;
  self->running = 0;

@{inStart}

   self->rst = 1;
   UPDATE(self);
   self->rst = 0;

#ifdef TRACE
   if(CreateVCD) tfp->dump(contextp->time());
   contextp->timeInc(1);
   if(CreateVCD) tfp->dump(contextp->time());
   contextp->timeInc(1);
#endif
}

static int cyclesDone = 0;

static void InternalUpdateAccelerator(){
   int baseAddress = 0;

   cyclesDone += 1;

   int sizeOfData = (@{databusDataSize} / 8);

   TopType* self = dut;

   // Databus must be updated before memories because databus could drive memories but memories "cannot" drive databus (in the sense that databus acts like a master if connected directly to memories but memories do not act like a master when connected to a databus. The unit logic is the one that acts like a master)

@{databusSim}
   
   baseAddress = 0;

   self->eval();
   UPDATE(self); // This line causes posedge clk events to activate

#ifdef TRACE
   if(CreateVCD) tfp->dump(contextp->time());
   contextp->timeInc(2);
#endif

// TODO: Technically only need to do this at the end of an accelerator run, do not need to do this every single update
@{saveState}
}

static bool IsDone(){
   TopType* self = dut;
       
  return @{done};
}

struct Once{};
struct _OnceTag{};
template<typename F>
Once operator+(_OnceTag t,F&& f){
  f();
  return Once{};
}

#define TEMP__once(LINE) TEMPonce_ ## LINE
#define TEMP_once(LINE) TEMP__once( LINE )
#define once static Once TEMP_once(__LINE__) = _OnceTag() + [&]()

@{declareExtraConfigs}

extern "C" void VersatReset(){
  @{resetExtraConfigs}
}

static void InternalStartAccelerator(){
  TopType* self = dut;

@{internalStart}

  self->run = 1;
  UPDATE(self);
  self->running = 1;
  self->run = 0;

#ifdef TRACE
  if(CreateVCD) tfp->dump(contextp->time());
  contextp->timeInc(1);
  if(CreateVCD) tfp->dump(contextp->time());
  contextp->timeInc(1);
#endif
}

static void InternalEndAccelerator(){
  TopType* self = dut;

  self->running = 0;

  // TODO: Is this update call needed?
  InternalUpdateAccelerator();

  // TODO: We could put the copy of state variables here
}

extern "C" int VersatAcceleratorCyclesElapsed(){
  return cyclesDone;
}

extern "C" void VersatAcceleratorSimulate(){
  InternalStartAccelerator();

  for(int i = 0; !IsDone() ; i++){
    InternalUpdateAccelerator();

    if(i >= 10000000){
      versat_printf("Accelerator simulation has surpassed 10000000 cycles for a single run\n");
      versat_printf("Assuming that the accelerator is stuck in a never ending loop\n");
      versat_printf("Terminating simulation\n");
      fflush(stdout);
      exit(-1);
    }   
  }

  InternalEndAccelerator();
}

extern "C" int MemoryAccess(int address,int value,int write){
  TopType* self = dut;

@{memoryAccessDefines}

  int actualAddress = address;

@{memoryUnpack}

#ifdef HAS_MEMORY_MAP
  if(write){
    @{memorySetValid}

    self->wstrb = 0xf;

    #ifdef MEMORY_MAP_BITS
      self->addr = actualAddress;
    #endif
      self->wdata = value;

      self->eval();

      //while(!self->ready){ For now we assume all writes have no delay 
          InternalUpdateAccelerator();
      //}

      @{memoryUnsetValid}
      //self->valid = 0;
      self->wstrb = 0x00;
    #ifdef MEMORY_MAP_BITS
      self->addr = 0x00000000;
    #endif
      self->wdata = 0x00000000;

      InternalUpdateAccelerator();

      return 0;
   } else {
      @{memorySetValid}

      //self->valid = 1;
      self->wstrb = 0x0;
    #ifdef MEMORY_MAP_BITS
      self->addr = actualAddress;
    #endif

      self->eval();

      while(!self->rvalid){
          InternalUpdateAccelerator();
      }

      int res = self->rdata;

      @{memoryUnsetValid}
      //self->valid = 0;
    #ifdef MEMORY_MAP_BITS
      self->addr = 0;
    #endif

      self->eval();
      while(self->rvalid){
          InternalUpdateAccelerator();
      }

      return res;
   }
#endif
   return 0;
}

extern "C" void VersatSignalLoop(){
   TopType* self = dut;

#ifdef SIGNAL_LOOP
   self->signal_loop = 1;
   InternalUpdateAccelerator();
   self->signal_loop = 0;
   self->eval();
#endif
}

extern "C" void VersatLoadDelay(volatile const unsigned int* delayBuffer){
  TopType* self = dut;

@{setDelays}
}

void VERSAT_DisableReadsAndWrites(){
@{disableReadsAndWrites}
}

// ============================================================================
// Start of Versat public interface

#if 1
#include "versat_accel.h"

#ifdef __cplusplus
#include <cstdio>
#include <cstdlib>
#include <cstring>
#else
#define nullptr 0
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#endif

#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof(arr[0]))

iptr versat_base;

#ifdef __cplusplus
extern "C"{
#endif

// Functions exported by wrapper that allow the accelerator to be simulated
int VersatAcceleratorCyclesElapsed();
void VersatReset();
void InitializeVerilator();
void VersatAcceleratorCreate();
void VersatAcceleratorSimulate();
void VersatSignalLoop();
int MemoryAccess(int address,int value,int write);

int GetAcceleratorCyclesElapsed();

#ifdef __cplusplus
  }
#endif

void ConfigEnableDMA(bool value){
}

void ConfigCreateVCD(bool value){
  CreateVCD = value;
}

void ConfigSimulateDatabus(bool value){
  SimulateDatabus = value;
}

void versat_init(int base){
  versatInitialized = true;
  CreateVCD = true;
  SimulateDatabus = true;
  versat_base = base;

  InitializeVerilator();
  VersatAcceleratorCreate();

  VersatLoadDelay(delayBuffer);
  
  accelStatic = &staticBuffer;
}

void SetVersatDebugPrintfFunction(VersatPrintf function){
  versat_printf = function;
}

static void CheckVersatInitialized(){
  if(!versatInitialized){
    versat_printf("Versat has not been initialized\n");
    fflush(stdout);
    exit(-1);
  }
}

void ResetAccelerator(){
  VersatReset();
  VersatLoadDelay(delayBuffer);
}

void SignalLoop(){
  VersatSignalLoop();
}

int GetAcceleratorCyclesElapsed(){
  return VersatAcceleratorCyclesElapsed();
}

void RunAccelerator(int times){
  CheckVersatInitialized();

  for(int i = 0; i < times; i++){
    VersatAcceleratorSimulate();
  }
}

void StartAccelerator(){
  CheckVersatInitialized();

  VersatAcceleratorSimulate();
}

void EndAccelerator(){
  // Do nothing. Start accelerator does everything, for now
}

void VersatMemoryCopy(volatile void* dest,volatile const void* data,int size){
  CheckVersatInitialized();

  char* versatStart = (char*) versat_base;
  char* versatEnd = versatStart + versatAddressSpace;
  
  char* destChar = (char*) dest;
  char* dataChar = (char*) data;

  bool destInsideVersat = (destChar >= versatStart && destChar < versatEnd);
  bool dataInsideVersat = (dataChar >= versatStart && dataChar < versatEnd);

  if(destInsideVersat == true && dataInsideVersat == true){
    versat_printf("VersatMemoryCopy is not capable of performing copies from Versat to Versat");
    return;
  } 

  if(destInsideVersat == false && dataInsideVersat == false){
    memcpy((void*) dest,(void*) data,size);
    return;
  }

  if(destInsideVersat){
    char* configView = (char*) accelConfig;
    bool destInsideConfig = (destChar >= configView && destChar < configView + AcceleratorConfigSize);
    
    int* dataView = (int*) data;

    // TODO: We technically also have to check for static and delay and stuff like that.
    if(destInsideConfig){
      memcpy((void*) dest,(void*) data,size);
    } else {
      for(int i = 0; i < (size / 4); i++){
        VersatUnitWrite(dest,i,dataView[i]);
      }
    }
  } else {
    int* destView = (int*) dest;
  
    for(int i = 0; i < (size / 4); i++){
      destView[i] = VersatUnitRead(data,i);
    }
  } 
}

void VersatUnitWrite(volatile const void* baseaddr,int index,int val){
  CheckVersatInitialized();

  iptr addr = (iptr) baseaddr + (index * sizeof(int)) - (versat_base + memMappedStart); // Convert back to zero based address
  MemoryAccess(addr,val,1);
}

int VersatUnitRead(volatile const void* baseaddr,int index){
  CheckVersatInitialized();

  iptr addr = (iptr) baseaddr + (index * sizeof(int)) - (versat_base + memMappedStart); // Convert back to zero based byte space address
  int res = MemoryAccess(addr,0,0);
  return res;
}

float VersatUnitReadFloat(volatile const void* base,int index){
  int res = VersatUnitRead(base,index);
  float* view = (float*) &res;
  return *view;
}

// ======================================
// Debug stuff currently disabled for pc-emul, altough we could do something in here to provide some data back.

void DebugRunAccelerator(int times, int maxCycles){
  RunAccelerator(times);
} 

VersatDebugState VersatDebugGetState(){
  return (VersatDebugState){};
}

VersatProfile VersatProfileGet(){
  return (VersatProfile){};
}

void VersatPrintProfile(VersatProfile p){
}

void VersatProfileReset(){

}

#endif